### ISSUE TITLE
Anpassen gettogether.community

### ISSUE THREAD

**Issue by weberius** [codeforcologne/Lab#8]
Das OK Lab hat in gettogether einen account: https://gettogether.community/codeforcologne/
Dieser ist umständlich im Editieren, trägt eher nicht zur Planung der Treffen bei und macht es uns schwer, zu erkennen wer kommt. 

Der Account soll stillgelegt, aber nicht gelöscht werden. D.h. die Terminserie wird abgebrochen und in der Beschreibung wird auf meetup.com verwiesern.

- [x] Terminserie abbrechen
- [ ] Kommentar anpassen

**Comment by muescha** [comment]
[ ] webseite https://codefor.de/koeln/ anpassen (Link "Termine" und Link im Fließtext) (source: {wo ist Homepage Repo?})
